- name: Install DHCP Server
  package:
    name: 
      - "{{ dhcp_package }}"
    state: latest

- name: Config DHCP Server
  become: yes
  template:
    src: "{{ dhcp_template_file }}"
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
  notify: Restart DHCP
  when: ansible_distribution == "Ubuntu"
